# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab44280f290578f266ab6ea95516bed25b5a61bc317da78627ab54f12564248309550f7200cf1f9b995d42d3c954a0e6cb15d2689e6711c3cfca85708c17e0fc

test:
  secret_key_base: 231e5cc27aae45672241c7fad8b371ac9a814be042ed44b2144a73df6e7d62929c6b318dd2270cdac0e61ea3d76ef5d948d415169fc67241add65fa0296255bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
